name: instagram_story_view
description: Instagram-like story view with hero expand animation for Flutter.
version: 0.1.0
homepage: https://github.com/Muhammad-Zaripov/instagram_story_view
repository: https://github.com/Muhammad-Zaripov/instagram_story_view

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
